# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import thread

class Ui_MainWindow(object):
    def initUI(self):
        self.lbl=QLabel(self)
        pixmap=QPixmap("profile.png")
        self.lbl.setPixmap(QPixmap(pixmap))
        self.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 607)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 301, 301))
        self.label.setObjectName("label")
        self.gender = QtWidgets.QComboBox(self.centralwidget)
        self.gender.setGeometry(QtCore.QRect(360, 40, 101, 31))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(10)
        self.gender.setFont(font)
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.addItem("")
        self.age = QtWidgets.QComboBox(self.centralwidget)
        self.age.setGeometry(QtCore.QRect(360, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(10)
        self.age.setFont(font)
        self.age.setObjectName("age")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(520, 30, 191, 51))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(12)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setGeometry(QtCore.QRect(520, 100, 191, 51))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(12)
        self.stop_btn.setFont(font)
        self.stop_btn.setObjectName("stop_btn")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 350, 691, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.status = QtWidgets.QLineEdit(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(360, 230, 151, 81))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(36)
        self.status.setFont(font)
        self.status.setText("")
        self.status.setObjectName("status")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(560, 230, 151, 81))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(36)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 180, 141, 41))
        font = QtGui.QFont()
        font.setFamily("배달의민족 도현")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 747, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.start_btn.clicked.connect(self.select_g)
        self.start_btn.clicked.connect(self.select_a)
        self.start_btn.clicked.connect(thread.detect_blink)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/profile.png\"/></p></body></html>"))
        self.gender.setItemText(0, _translate("MainWindow", "여성"))
        self.gender.setItemText(1, _translate("MainWindow", "남성"))
        self.age.setItemText(0, _translate("MainWindow", "10대"))
        self.age.setItemText(1, _translate("MainWindow", "20대"))
        self.age.setItemText(2, _translate("MainWindow", "30대"))
        self.age.setItemText(3, _translate("MainWindow", "40대"))
        self.age.setItemText(4, _translate("MainWindow", "50대"))
        self.age.setItemText(5, _translate("MainWindow", "60대"))
        self.age.setItemText(6, _translate("MainWindow", "70대"))
        self.age.setItemText(7, _translate("MainWindow", "80대"))
        self.age.setItemText(8, _translate("MainWindow", "90대"))
        self.start_btn.setText(_translate("MainWindow", "측정 시작"))
        self.stop_btn.setText(_translate("MainWindow", "측정 중지"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">현재 상태</p></body></html>"))
    
    def select_g(self):
        gender=self.gender.currentText()
        print(self.gender.currentText())
    
    def select_a(self):
        age=self.age.currentText()
        print(self.age.currentText())

import source

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
