# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import thread
import time
from threading import Thread
import GUI_main
photo1="resource\image\profile.png"
photo2="resource\image\profile2.png"
phototemp=""


class Thread1(QThread):
    def __init__(self, parent):
        super().__init__(parent)
    def run(self):
        thread.detect_blink()

class Thread2(QThread):
    vid = GUI_main.ShowVideo()
    image_viewer1 = GUI_main.ImageViewer()
    vid.VideoSignal1.connect(image_viewer1.setImage)
    def __init__(self, parent):
        super().__init__(parent)
    def run(self):
        self.vid.startVideo()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(738, 872)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(738, 932))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_5)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.start_btn = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_btn.sizePolicy().hasHeightForWidth())
        self.start_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(12)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.gridLayout_3.addWidget(self.start_btn, 0, 0, 1, 1)
        self.stop_btn = QtWidgets.QPushButton(self.widget_3)
        self.stop_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_btn.sizePolicy().hasHeightForWidth())
        self.stop_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(12)
        self.stop_btn.setFont(font)
        self.stop_btn.setDefault(False)
        self.stop_btn.setFlat(False)
        self.stop_btn.setObjectName("stop_btn")
        self.gridLayout_3.addWidget(self.stop_btn, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_3, 0, 1, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("배달의민족 도현")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.graphic_show_btn = QtWidgets.QPushButton(self.widget_4)
        self.graphic_show_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphic_show_btn.sizePolicy().hasHeightForWidth())
        self.graphic_show_btn.setSizePolicy(sizePolicy)
        self.graphic_show_btn.setMinimumSize(QtCore.QSize(141, 0))
        self.graphic_show_btn.setObjectName("graphic_show_btn")
        self.gridLayout_4.addWidget(self.graphic_show_btn, 0, 1, 1, 1)
        self.graphic_hide_btn = QtWidgets.QPushButton(self.widget_4)
        self.graphic_hide_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphic_hide_btn.sizePolicy().hasHeightForWidth())
        self.graphic_hide_btn.setSizePolicy(sizePolicy)
        self.graphic_hide_btn.setMinimumSize(QtCore.QSize(140, 0))
        self.graphic_hide_btn.setObjectName("graphic_hide_btn")
        self.gridLayout_4.addWidget(self.graphic_hide_btn, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("배달의민족 도현")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("resource/image/Soso.png"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_4, 1, 0, 1, 2)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gender = QtWidgets.QComboBox(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(10)
        self.gender.setFont(font)
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.addItem("")
        self.gridLayout_2.addWidget(self.gender, 0, 0, 1, 1)
        self.age = QtWidgets.QComboBox(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(10)
        self.age.setFont(font)
        self.age.setObjectName("age")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.age.addItem("")
        self.gridLayout_2.addWidget(self.age, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget, 0, 2, 4, 1)
        self.Profile_change = QtWidgets.QPushButton(self.widget_5)
        self.Profile_change.setEnabled(True)
        self.Profile_change.setMaximumSize(QtCore.QSize(40, 40))
        self.Profile_change.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/image/change.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Profile_change.setIcon(icon)
        self.Profile_change.setObjectName("Profile_change")
        self.gridLayout_5.addWidget(self.Profile_change, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 300))
        self.label.setLineWidth(0)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("resource/image/profile.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 2)
        self.gridLayout_7.addWidget(self.widget_5, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setMinimumSize(QtCore.QSize(720, 480))
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget_6)
        self.graphicsView.setMinimumSize(QtCore.QSize(700, 460))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_6.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_6, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.graphic_show_btn.clicked.connect(self.show_graphic)
        self.graphic_hide_btn.clicked.connect(self.hide_graphic)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "프로필 사진을 변경하려면 다음 버튼을 누르십시오."))
        self.start_btn.setText(_translate("MainWindow", "측정 시작"))
        self.stop_btn.setText(_translate("MainWindow", "측정 중지"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">현재 상태</span></p></body></html>"))
        self.graphic_show_btn.setText(_translate("MainWindow", "그래프 나타내기"))
        self.graphic_hide_btn.setText(_translate("MainWindow", "그래프 숨기기"))
        self.gender.setItemText(0, _translate("MainWindow", "여성"))
        self.gender.setItemText(1, _translate("MainWindow", "남성"))
        self.age.setItemText(0, _translate("MainWindow", "10대"))
        self.age.setItemText(1, _translate("MainWindow", "20대"))
        self.age.setItemText(2, _translate("MainWindow", "30대"))
        self.age.setItemText(3, _translate("MainWindow", "40대"))
        self.age.setItemText(4, _translate("MainWindow", "50대"))
        self.age.setItemText(5, _translate("MainWindow", "60대"))
        self.age.setItemText(6, _translate("MainWindow", "70대"))
        self.age.setItemText(7, _translate("MainWindow", "80대"))
        self.age.setItemText(8, _translate("MainWindow", "90대"))

    def show_graphic(self):
        self.graphic_hide_btn.setEnabled(True)
        self.graphic_show_btn.setEnabled(False)
        self.widget_6.show()
        self.centralwidget.setFixedSize(738,852)
        MainWindow.setFixedSize(738,872) 

    def hide_graphic(self):
        self.graphic_hide_btn.setEnabled(False)
        self.graphic_show_btn.setEnabled(True)
        self.widget_6.hide()
        self.centralwidget.setFixedSize(738,408)
        MainWindow.setFixedSize(738,428)

    def db_starter(self):
        x = Thread1(self)
        x.start()
    def us_starter(self):
        y = Thread(target = self.update_status, args=())
        y.start()
    def gp_starter(self):
        z = Thread2(self)
        z.start()
    def gp_updater(self):
        w = Thread(target = self.update_gp, args=())
        w.start()
    def change_profile(self):
        global photo1, photo2, phototemp
        self.label.setPixmap(QtGui.QPixmap(photo2))
        phototemp=photo1
        photo1=photo2
        photo2=phototemp
    
    def select_g(self):
        global gender
        gender=self.gender.currentText()
        print(self.gender.currentText())
    
    def select_a(self):
        global age
        age=self.age.currentText()
        print(self.age.currentText())
        
    def update_status(self):
        while(True):
            time.sleep(10)
            cnt_blink = thread.cnt_blink
            if(cnt_blink <=1):
                self.label_3.setPixmap(QtGui.QPixmap("resource\\image\\bad.png"))
            elif(1 < cnt_blink <=3):
                self.label_3.setPixmap(QtGui.QPixmap("resource\\image\\Soso.png"))
            elif(cnt_blink >3):
                self.label_3.setPixmap(QtGui.QPixmap("resource\\image\\Good.png"))

    def update_gp(self):
        while(True):
            time.sleep(10)
            self.graphicsView.setPixmap(QtGui.QPixmap("dataset/graph.jpg"))

app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
ui.widget_6.hide()
ui.centralwidget.setFixedSize(738,408)
MainWindow.setFixedSize(738,428)
sys.exit(app.exec_())
